### PR TITLE
Update for 0.7

### PR DESCRIPTION
**Pull request by ghost**
I haven't tested this but it's compiling with 0.7 now.

### CODE REVIEW

**Comment by pelotom** [comment]
The current best way to test this library is using the [purescript-d3-examples](https://github.com/pelotom/purescript-d3-examples) project, and that will probably also require a PR to make it work with PS 0.7 (which I'm having cabal problems trying to install right now).

**Comment by paf31** [comment]
It's not on Hackage yet, you'd be better off installing from `master`.

**Comment by pelotom** [comment]
@paf31 I was trying to install off of `master`... I just realized I'm on GHC 7.10, so that might be a problem, but the error I got didn't seem related to that:

```
cabal: Error: some packages failed to install:
purescript-0.7.0.0 depends on safe-0.3.9 which failed to install.
safe-0.3.9 failed while downloading the package. The exception was:
/Users/tom/Library/Haskell/repo-cache/hackage.haskell.org/safe/0.3.9/safe-0.3.9.tar.gz.etag:
openFile: does not exist (No such file or directory)
```

**Comment by paf31** [comment]
Hmm, I've not seen that before. Seems like a cabal issue?

**Comment by pelotom** [comment]
¯\_(ツ)_/¯

**Comment by ghost** [comment]
@pelotom I'll try and test with your examples repo and maybe submit a PR. As for building purescript, I was able to get it to work from master last night using GHC `7.10.1` on OS X, though I did have some problems getting it to work earlier that appear unrelated to what you describe. In my case I think it was a problem with the sandbox because when I cloned a fresh repo and tried again it worked.

**Comment by nwolverson** [comment]
Need to do something about `bind` which is now used in the Prelude including desugaring `do` blocks.

**Comment by nwolverson** [comment]
Submitted an update to the examples repo and a small change that could be brought into this PR https://github.com/freebroccolo/purescript-d3/pull/1 - but to get things to work I had to rename `bind`, I think you may want to suggest a better name.

**Comment by pelotom** [comment]
It's funny that `bind` itself was renamed from D3's `data` because of a keyword conflict with purescript... and now they've taken `bind` from us! So I split the difference and called it `bindData` now :)

Thanks for all your help, guys!

**Comment by nwolverson** [comment]
Great :+1:

**Pull request merged**
